### ISSUE TITLE
Replace `var.s3_website_password_enabled` with Bucket Policy and CloudFront OAI

### ISSUE THREAD

**Issue by sebastianmacarescu** [cloudposse/terraform-aws-cloudfront-s3-cdn#184]
## Describe the Feature

For `var.website_enabled` we should be able to use a Bucket Policy and an [CloudFront OAI](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html) to make the bucket private and allow access only to CloudFront, rather than be limited to `var.s3_website_password_enabled`.

Example bucket policy:
```json
{
  "Version": "2012-10-17",
  "Id": "PolicyForCloudFrontPrivateContent",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": ${jsonencode(dependency.cloudfront.outputs.cloudfront_origin_access_identity_iam_arns)}
      },
      "Action": "s3:GetObject",
      "Resource": "arn:aws:s3:::${local.bucket_name}/*"
    }
  ]
}
```

**Comment by joshmello** [comment]
+1

**Comment by korenyoni** [comment]
@sebastianmacarescu sorry for the delay on this.

I've taken the liberty to edit the description and title for this issue to make it a bit more thorough. If I've misunderstood or misrepresented anything, please edit it again.

If I understand correctly, the feature request is to allow the use of a CloudFront OAI when `var.website_enabled` is `true`?

According to the CloudFront documentation, this is not possible (see: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html):

> If you use an Amazon S3 bucket configured as a website endpoint, you must set it up with CloudFront as a custom origin. You can’t use the origin access identity feature described in this topic. However, you can restrict access to content on a custom origin by setting up custom headers and configuring your origin to require them. For more information, see Restricting access to files on custom origins.

If one wishes to use the bucket policy and CloudFront OAI, they must set `var.website_enabled` to false. Then, the CF distribution will use an S3 origin rather than a custom origin (S3 website) with a bucket policy and CloudFront OAI in the said policy.

**Comment by korenyoni** [comment]
@sebastianmacarescu sorry for the delay on this.

I've taken the liberty to edit the description and title for this issue to make it a bit more thorough. If I've misunderstood or misrepresented anything, please edit it again.

**Comment by korenyoni** [comment]
If I understand correctly, the feature request is to allow the use of a CloudFront OAI when `var.website_enabled` is `true`.

According to the CloudFront documentation, this is not possible (see: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html):

> If you use an Amazon S3 bucket configured as a website endpoint, you must set it up with CloudFront as a custom origin. You can’t use the origin access identity feature described in this topic. However, you can restrict access to content on a custom origin by setting up custom headers and configuring your origin to require them. For more information, see Restricting access to files on custom origins.

If one wishes to use the bucket policy and CloudFront OAI, they must set `var.website_enabled` to false. Then, the CF distribution will use an S3 origin rather than a custom origin (S3 website) with a bucket policy and CloudFront OAI in the said policy.

This is done in the following places:

https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/blob/64bd6d97d0d1a07e5bd354513856e031dccfe1d1/main.tf#L102-L106

https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/blob/64bd6d97d0d1a07e5bd354513856e031dccfe1d1/main.tf#L32-L43

https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/blob/64bd6d97d0d1a07e5bd354513856e031dccfe1d1/main.tf#L115-L143

If I've misunderstood anything please feel free to update the thread, edit the description, and/or reopen the issue.

**Comment by sebastianmacarescu** [comment]
Thank you very much @korenyoni for the explanation. I have missed that.
